import pandas as pd

countries = [
    "Europe",
    "Asia",
    "Americas",
    "All",
    "Sub-Saharan Africa",
    "Latin America and the Caribbean",
    "Northern America",
    "South-eastern Asia",
    "Southern Asia",
    "Western Asia",
    "Eastern Europe",
    "Northern Europe",
    "Southern Europe",
    "Western Europe",
    "Australia",
    "Canada",
    "China, Hong Kong Special Administrative Region",
    "Singapore",
    "USA, Puerto Rico and US Virgin Islands",
    "Argentina",
    "Spain",
    "French Polynesia",
    "Thailand",
    "Japan",
    "China",
    "Taiwan and other Asia, nes.",
    "Indonesia",
    "Turkey",
    "Unknown",
    "Ecuador",
    "Lao People's Dem. Rep.",
    "Sri Lanka",
    "Kuwait",
    "New Zealand",
    "Melanesia",
    "Pacific Islands Countries and Territories",
    "Australia and New Zealand",
    "Africa",
    "Eastern Asia",
    "Malaysia",
    "Paraguay",
    "Kenya",
    "Vanuatu",
    "Portugal",
    "Viet Nam",
    "Hungary",
    "Southern African Customs Union",
    "Sudan",
    "Philippines",
    "Germany",
    "Papua New Guinea",
    "Andorra",
    "Ukraine",
    "Polynesia",
    "Oceania",
    "United Kingdom",
    "Republic of Korea",
    "Tonga",
    "Costa Rica",
    "Colombia",
    "Chile",
    "Poland",
    "Slovenia",
    "Uganda",
    "Switzerland, Liechtenstein",
    "Pakistan",
    "Mexico",
    "Ethiopia",
    "Gambia",
    "United Arab Emirates",
    "France, Monaco",
    "Cook Islands",
    "Brazil",
    "Samoa",
    "Bulgaria",
    "Fiji",
    "Guam",
    "Morocco",
    "Iran",
    "Northern Mariana Islands",
    "Solomon Islands",
    "New Caledonia",
    "Italy",
    "Republic of Moldova",
    "Belgium-Luxembourg",
    "Ireland",
    "Netherlands",
    "Marshall Islands",
    "Latvia",
    "Norway, Svalbard and Jan Mayen",
    "Greece",
    "India",
    "Austria",
    "Micronesia",
    "Denmark",
    "Kazakhstan",
    "Saudi Arabia",
    "Democratic People's Republic of Korea",
    "Palau",
    "Jamaica",
    "Bahrain",
    "Egypt",
    "Myanmar",
    "American Samoa",
    "Croatia",
    "Lithuania",
    "Chad",
    "Niger",
    "Northern Africa",
    "Czechia",
    "Saint Kitts and Nevis",
    "Panama",
    "Peru",
    "Serbia and Montenegro",
    "Algeria",
    "Syria",
    "Romania",
    "Bangladesh",
    "Lebanon",
    "Israel",
    "Trinidad and Tobago",
    "Federated State of Micronesia",
    "Estonia",
    "Russian Federation",
    "The Former Yugoslav Republic of Macedonia",
    "Plurinational State of Bolivia",
    "Barbados",
    "Dominican Republic",
    "Sweden",
    "Suriname",
    "Equatorial Guinea",
    "Senegal",
    "Tunisia",
    "British Virgin Islands",
    "El Salvador",
    "Uzbekistan",
    "Benin",
    "Malta",
    "Netherlands Antilles",
    "Cyprus",
    "Oman",
    "Antigua and Barbuda",
    "Dominica",
    "Curaçao",
    "Slovakia",
    "Armenia",
    "Madagascar",
    "Kyrgyzstan",
    "Georgia",
    "Guyana",
    "Central Asia",
    "Finland",
    "Cambodia",
    "Serbia",
    "Anguilla",
    "Uruguay",
    "Belize",
    "Côte d'Ivoire",
    "China, Macao Special Administrative Region",
    "Sao Tome and Principe",
    "Azerbaijan",
    "Mongolia",
    "Cuba",
    "Montserrat",
    "Mauritius",
    "Iraq",
    "Albania",
    "Mozambique",
    "Kiribati",
    "Liberia",
    "Comoros",
    "Mali",
    "Venezuela",
    "Sierra Leone",
    "Iceland",
    "Nepal",
    "Brunei Darussalam",
    "Tuvalu",
    "Guatemala",
    "Nicaragua",
    "Montenegro",
    "Cameroon",
    "Niue",
    "Mauritania",
    "Honduras",
    "Saint Lucia",
    "Belarus",
    "Bosnia Herzegovina",
    "Bahamas",
    "Jordan",
    "Zimbabwe",
    "Seychelles",
    "Yemen",
    "Switzerland",
    "Malawi",
    "Wallis and Futuna Islands",
    "Afghanistan",
    "Nauru",
    "United Republic of Tanzania",
    "Greenland",
    "Cocos Islands",
    "Central African Republic",
    "Bonaire, Saint Eustatius and Saba",
    "Burundi",
    "Ghana",
    "Togo",
    "Guinea",
    "British Indian Ocean Territories",
    "Cabo Verde",
    "Saint Helena",
    "Zambia",
    "Turkmenistan",
    "Nigeria",
    "Timor-Leste",
    "Rwanda",
]
