import pandas as pd

unseen = [
    "Federated State of Micronesia",
    "Americas",
    "Africa",
    "All",
    "Taiwan and other Asia, nes.",
    "Northern America",
    "Eastern Asia",
    "Eastern Europe",
    "Northern Europe",
    "Western Europe",
    "France, Monaco",
    "Melanesia",
    "Micronesia",
    "Polynesia",
    "Pacific Islands Countries and Territories",
    "Oceania",
    "Iran",
    "South-eastern Asia",
    "USA, Puerto Rico and US Virgin Islands",
    "PICT Unknown",
    "Asia",
    "Latin America and the Caribbean",
    "Unknown",
    "United Kingdom",
    "Europe",
    "Sub-Saharan Africa",
    "Southern Asia",
    "Belgium-Luxembourg",
    "Switzerland, Liechtenstein",
    "Southern African Customs Union",
    "Netherlands Antilles",
    "Western Asia",
    "Syria",
    "Norway, Svalbard and Jan Mayen",
    "The Former Yugoslav Republic of Macedonia",
    "Southern Europe",
    "Australia and New Zealand",
    "Bosnia Herzegovina",
    "Serbia and Montenegro",
    "Cocos Islands",
    "Northern Africa",
    "Norfolk Islands",
    "Lao People's Dem. Rep.",
    "Central Asia",
]

pd.DataFrame(unseen)

un = sorted(unseen)

un = [
    # "Africa",
    # "All",
    # "Americas",
    "Asia",
    "Australia and New Zealand",
    "Belgium-Luxembourg",
    "Bosnia Herzegovina",
    "Central Asia",
    "Cocos Islands",
    "Eastern Asia",
    "Eastern Europe",
    "Europe",
    "Federated State of Micronesia",
    "France, Monaco",
    "Iran",
    "Lao People's Dem. Rep.",
    "Latin America and the Caribbean",
    "Melanesia",
    "Micronesia",
    "Netherlands Antilles",
    "Norfolk Islands",
    "Northern Africa",
    "Northern America",
    "Northern Europe",
    "Norway, Svalbard and Jan Mayen",
    "Oceania",
    "PICT Unknown",
    "Pacific Islands Countries and Territories",
    "Polynesia",
    "Serbia and Montenegro",
    "South-eastern Asia",
    "Southern African Customs Union",
    "Southern Asia",
    "Southern Europe",
    "Sub-Saharan Africa",
    "Switzerland, Liechtenstein",
    "Syria",
    "Taiwan and other Asia, nes.",
    "The Former Yugoslav Republic of Macedonia",
    "USA, Puerto Rico and US Virgin Islands",
    "United Kingdom",
    "Unknown",
    "Western Asia",
    "Western Europe",
]

possible_territories = [
    "Micronesia",
    "Melanesia",
    "Polynesia",
    "Wallis and Futuna Islands",
    "Tokelau",
    "American Samoa",
    "Guam",
    "Pitcairn",
    "Northern Mariana Islands",
]


not_countries = [
    "All",
    "Americas",
    "Latin America and the Caribbean",
    "Sub-Saharan Africa",
    "Melanesia",
    "Southern African Customs Union",
    "Eastern Asia",
    "Unknown",
    "Polynesia",
    "Northern America",
    "Sudan",
    "Western Asia",
    "Eastern Europe",
    "Northern Europe",
    "Southern Europe",
    "Northern Africa",
    "Pacific Islands Countries and Territories",
    "Australia and New Zealand",
    "Oceania",
    "Central Asia",
    "Northern Mariana Islands",
    "Republic of Moldova",
    "Democratic People's Republic of Korea",
    "Republic of Korea",
    "Switzerland, Liechtenstein",
    "China, Macao Special Administrative Region",
    "Turkmenistan",
    "Wallis and Futuna Islands",
    "Cocos Islands",
]


pacific_countries = {
    "country": [
        "Australia",
        "Cook Islands",
        "Federated State of Micronesia",
        "Fiji",
        "French Polynesia",
        "Tonga",
        "Kiribati",
        "Marshall Islands",
        "Micronesia",
        "Nauru",
        "New Caledonia",
        "New Zealand",
        "Niue",
        "Palau",
        "Papua New Guinea",
        "Samoa",
        "Solomon Islands",
        "Tuvalu",
        "Vanuatu",
    ]
}
